//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.31 at 01:35:41 PM CST 
//


package com.mozu.sterling.model.order;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "personInfo"
})
@XmlRootElement(name = "AdditionalAddress")
public class AdditionalAddress {

    @XmlAttribute(name = "AddressType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String addressType;
    @XmlAttribute(name = "EntityAddressKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String entityAddressKey;
    @XmlAttribute(name = "EntityKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String entityKey;
    @XmlAttribute(name = "EntityParentKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String entityParentKey;
    @XmlAttribute(name = "EntityType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String entityType;
    @XmlAttribute(name = "PersonInfoKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String personInfoKey;
    @XmlElement(name = "PersonInfo")
    protected ContactPersonInfo personInfo;

    /**
     * Gets the value of the addressType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressType() {
        return addressType;
    }

    /**
     * Sets the value of the addressType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressType(String value) {
        this.addressType = value;
    }

    /**
     * Gets the value of the entityAddressKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityAddressKey() {
        return entityAddressKey;
    }

    /**
     * Sets the value of the entityAddressKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityAddressKey(String value) {
        this.entityAddressKey = value;
    }

    /**
     * Gets the value of the entityKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityKey() {
        return entityKey;
    }

    /**
     * Sets the value of the entityKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityKey(String value) {
        this.entityKey = value;
    }

    /**
     * Gets the value of the entityParentKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityParentKey() {
        return entityParentKey;
    }

    /**
     * Sets the value of the entityParentKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityParentKey(String value) {
        this.entityParentKey = value;
    }

    /**
     * Gets the value of the entityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityType() {
        return entityType;
    }

    /**
     * Sets the value of the entityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityType(String value) {
        this.entityType = value;
    }

    /**
     * Gets the value of the personInfoKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonInfoKey() {
        return personInfoKey;
    }

    /**
     * Sets the value of the personInfoKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonInfoKey(String value) {
        this.personInfoKey = value;
    }

    /**
     * Gets the value of the personInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PersonInfo }
     *     
     */
    public ContactPersonInfo getPersonInfo() {
        return personInfo;
    }

    /**
     * Sets the value of the personInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonInfo }
     *     
     */
    public void setPersonInfo(ContactPersonInfo value) {
        this.personInfo = value;
    }

}
