//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.31 at 01:35:41 PM CST 
//


package com.mozu.sterling.model.order;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Coupon")
public class Coupon {

    @XmlAttribute(name = "AssignedUniqueCodes")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String assignedUniqueCodes;
    @XmlAttribute(name = "CodeFormat")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String codeFormat;
    @XmlAttribute(name = "CouponID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String couponID;
    @XmlAttribute(name = "CouponKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String couponKey;
    @XmlAttribute(name = "GenerateUniqueCodes")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String generateUniqueCodes;
    @XmlAttribute(name = "GenerationStatus")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String generationStatus;
    @XmlAttribute(name = "ImportUniqueCodes")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String importUniqueCodes;
    @XmlAttribute(name = "IsExclusive")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String isExclusive;
    @XmlAttribute(name = "NumberOfCodesToGenerate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String numberOfCodesToGenerate;
    @XmlAttribute(name = "OrganizationCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String organizationCode;
    @XmlAttribute(name = "PricingRuleKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pricingRuleKey;
    @XmlAttribute(name = "a-dtype")
    protected List<String> aDtype;

    /**
     * Gets the value of the assignedUniqueCodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignedUniqueCodes() {
        return assignedUniqueCodes;
    }

    /**
     * Sets the value of the assignedUniqueCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignedUniqueCodes(String value) {
        this.assignedUniqueCodes = value;
    }

    /**
     * Gets the value of the codeFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeFormat() {
        return codeFormat;
    }

    /**
     * Sets the value of the codeFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeFormat(String value) {
        this.codeFormat = value;
    }

    /**
     * Gets the value of the couponID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCouponID() {
        return couponID;
    }

    /**
     * Sets the value of the couponID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCouponID(String value) {
        this.couponID = value;
    }

    /**
     * Gets the value of the couponKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCouponKey() {
        return couponKey;
    }

    /**
     * Sets the value of the couponKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCouponKey(String value) {
        this.couponKey = value;
    }

    /**
     * Gets the value of the generateUniqueCodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenerateUniqueCodes() {
        return generateUniqueCodes;
    }

    /**
     * Sets the value of the generateUniqueCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenerateUniqueCodes(String value) {
        this.generateUniqueCodes = value;
    }

    /**
     * Gets the value of the generationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenerationStatus() {
        return generationStatus;
    }

    /**
     * Sets the value of the generationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenerationStatus(String value) {
        this.generationStatus = value;
    }

    /**
     * Gets the value of the importUniqueCodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportUniqueCodes() {
        return importUniqueCodes;
    }

    /**
     * Sets the value of the importUniqueCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportUniqueCodes(String value) {
        this.importUniqueCodes = value;
    }

    /**
     * Gets the value of the isExclusive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsExclusive() {
        return isExclusive;
    }

    /**
     * Sets the value of the isExclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsExclusive(String value) {
        this.isExclusive = value;
    }

    /**
     * Gets the value of the numberOfCodesToGenerate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfCodesToGenerate() {
        return numberOfCodesToGenerate;
    }

    /**
     * Sets the value of the numberOfCodesToGenerate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfCodesToGenerate(String value) {
        this.numberOfCodesToGenerate = value;
    }

    /**
     * Gets the value of the organizationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationCode() {
        return organizationCode;
    }

    /**
     * Sets the value of the organizationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationCode(String value) {
        this.organizationCode = value;
    }

    /**
     * Gets the value of the pricingRuleKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPricingRuleKey() {
        return pricingRuleKey;
    }

    /**
     * Sets the value of the pricingRuleKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPricingRuleKey(String value) {
        this.pricingRuleKey = value;
    }

    /**
     * Gets the value of the aDtype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aDtype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getADtype().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getADtype() {
        if (aDtype == null) {
            aDtype = new ArrayList<String>();
        }
        return this.aDtype;
    }

}
