//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.16 at 12:31:15 PM CDT 
//


package com.mozu.sterling.model.order;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orderTag"
})
@XmlRootElement(name = "OrderTags")
public class OrderTags {

    @XmlElement(name = "OrderTag")
    protected OrderTag orderTag;

    /**
     * Gets the value of the orderTag property.
     * 
     * @return
     *     possible object is
     *     {@link OrderTag }
     *     
     */
    public OrderTag getOrderTag() {
        return orderTag;
    }

    /**
     * Sets the value of the orderTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderTag }
     *     
     */
    public void setOrderTag(OrderTag value) {
        this.orderTag = value;
    }

}
