//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.31 at 01:35:41 PM CST 
//


package com.mozu.sterling.model.order;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paymentTransactionError"
})
@XmlRootElement(name = "PaymentTransactionErrorList")
public class PaymentTransactionErrorList {

    @XmlElement(name = "PaymentTransactionError")
    protected PaymentTransactionError paymentTransactionError;

    /**
     * Gets the value of the paymentTransactionError property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentTransactionError }
     *     
     */
    public PaymentTransactionError getPaymentTransactionError() {
        return paymentTransactionError;
    }

    /**
     * Sets the value of the paymentTransactionError property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentTransactionError }
     *     
     */
    public void setPaymentTransactionError(PaymentTransactionError value) {
        this.paymentTransactionError = value;
    }

}
