//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.16 at 12:31:15 PM CDT 
//


package com.mozu.sterling.model.order;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "PaymentDetails")
public class PaymentDetails {

    @XmlAttribute(name = "AuditTransactionId")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String auditTransactionId;
    @XmlAttribute(name = "AuthAvs")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String authAvs;
    @XmlAttribute(name = "AuthCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String authCode;
    @XmlAttribute(name = "AuthReturnCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String authReturnCode;
    @XmlAttribute(name = "AuthReturnFlag")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String authReturnFlag;
    @XmlAttribute(name = "AuthReturnMessage")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String authReturnMessage;
    @XmlAttribute(name = "AuthTime")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String authTime;
    @XmlAttribute(name = "AuthorizationExpirationDate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String authorizationExpirationDate;
    @XmlAttribute(name = "AuthorizationID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String authorizationID;
    @XmlAttribute(name = "CVVAuthCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String cvvAuthCode;
    @XmlAttribute(name = "CallForAuthorizationStatus")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String callForAuthorizationStatus;
    @XmlAttribute(name = "CashBackAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String cashBackAmount;
    @XmlAttribute(name = "ChargeType", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String chargeType;
    @XmlAttribute(name = "CollectionDate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String collectionDate;
    @XmlAttribute(name = "HoldAgainstBook")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String holdAgainstBook;
    @XmlAttribute(name = "InPerson")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String inPerson;
    @XmlAttribute(name = "InternalReturnCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String internalReturnCode;
    @XmlAttribute(name = "InternalReturnFlag")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String internalReturnFlag;
    @XmlAttribute(name = "InternalReturnMessage")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String internalReturnMessage;
    @XmlAttribute(name = "OfflineStatus")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String offlineStatus;
    @XmlAttribute(name = "PaymentEntryType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String paymentEntryType;
    @XmlAttribute(name = "ProcessedAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String processedAmount;
    @XmlAttribute(name = "Reference1")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String reference1;
    @XmlAttribute(name = "Reference2")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String reference2;
    @XmlAttribute(name = "RequestAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String requestAmount;
    @XmlAttribute(name = "RequestId")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String requestId;
    @XmlAttribute(name = "RequestProcessed")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String requestProcessed;
    @XmlAttribute(name = "TranRequestTime")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tranRequestTime;
    @XmlAttribute(name = "TranReturnCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tranReturnCode;
    @XmlAttribute(name = "TranReturnFlag")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tranReturnFlag;
    @XmlAttribute(name = "TranReturnMessage")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tranReturnMessage;
    @XmlAttribute(name = "TranType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tranType;
    @XmlAttribute(name = "VoidTransaction")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String voidTransaction;
    @XmlAttribute(name = "a-dtype")
    protected List<String> aDtype;

    /**
     * Gets the value of the auditTransactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuditTransactionId() {
        return auditTransactionId;
    }

    /**
     * Sets the value of the auditTransactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuditTransactionId(String value) {
        this.auditTransactionId = value;
    }

    /**
     * Gets the value of the authAvs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthAvs() {
        return authAvs;
    }

    /**
     * Sets the value of the authAvs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthAvs(String value) {
        this.authAvs = value;
    }

    /**
     * Gets the value of the authCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * Sets the value of the authCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthCode(String value) {
        this.authCode = value;
    }

    /**
     * Gets the value of the authReturnCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthReturnCode() {
        return authReturnCode;
    }

    /**
     * Sets the value of the authReturnCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthReturnCode(String value) {
        this.authReturnCode = value;
    }

    /**
     * Gets the value of the authReturnFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthReturnFlag() {
        return authReturnFlag;
    }

    /**
     * Sets the value of the authReturnFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthReturnFlag(String value) {
        this.authReturnFlag = value;
    }

    /**
     * Gets the value of the authReturnMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthReturnMessage() {
        return authReturnMessage;
    }

    /**
     * Sets the value of the authReturnMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthReturnMessage(String value) {
        this.authReturnMessage = value;
    }

    /**
     * Gets the value of the authTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthTime() {
        return authTime;
    }

    /**
     * Sets the value of the authTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthTime(String value) {
        this.authTime = value;
    }

    /**
     * Gets the value of the authorizationExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizationExpirationDate() {
        return authorizationExpirationDate;
    }

    /**
     * Sets the value of the authorizationExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizationExpirationDate(String value) {
        this.authorizationExpirationDate = value;
    }

    /**
     * Gets the value of the authorizationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizationID() {
        return authorizationID;
    }

    /**
     * Sets the value of the authorizationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizationID(String value) {
        this.authorizationID = value;
    }

    /**
     * Gets the value of the cvvAuthCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCVVAuthCode() {
        return cvvAuthCode;
    }

    /**
     * Sets the value of the cvvAuthCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCVVAuthCode(String value) {
        this.cvvAuthCode = value;
    }

    /**
     * Gets the value of the callForAuthorizationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallForAuthorizationStatus() {
        return callForAuthorizationStatus;
    }

    /**
     * Sets the value of the callForAuthorizationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallForAuthorizationStatus(String value) {
        this.callForAuthorizationStatus = value;
    }

    /**
     * Gets the value of the cashBackAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCashBackAmount() {
        return cashBackAmount;
    }

    /**
     * Sets the value of the cashBackAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCashBackAmount(String value) {
        this.cashBackAmount = value;
    }

    /**
     * Gets the value of the chargeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeType() {
        return chargeType;
    }

    /**
     * Sets the value of the chargeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeType(String value) {
        this.chargeType = value;
    }

    /**
     * Gets the value of the collectionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollectionDate() {
        return collectionDate;
    }

    /**
     * Sets the value of the collectionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollectionDate(String value) {
        this.collectionDate = value;
    }

    /**
     * Gets the value of the holdAgainstBook property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoldAgainstBook() {
        return holdAgainstBook;
    }

    /**
     * Sets the value of the holdAgainstBook property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoldAgainstBook(String value) {
        this.holdAgainstBook = value;
    }

    /**
     * Gets the value of the inPerson property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInPerson() {
        return inPerson;
    }

    /**
     * Sets the value of the inPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInPerson(String value) {
        this.inPerson = value;
    }

    /**
     * Gets the value of the internalReturnCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalReturnCode() {
        return internalReturnCode;
    }

    /**
     * Sets the value of the internalReturnCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalReturnCode(String value) {
        this.internalReturnCode = value;
    }

    /**
     * Gets the value of the internalReturnFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalReturnFlag() {
        return internalReturnFlag;
    }

    /**
     * Sets the value of the internalReturnFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalReturnFlag(String value) {
        this.internalReturnFlag = value;
    }

    /**
     * Gets the value of the internalReturnMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalReturnMessage() {
        return internalReturnMessage;
    }

    /**
     * Sets the value of the internalReturnMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalReturnMessage(String value) {
        this.internalReturnMessage = value;
    }

    /**
     * Gets the value of the offlineStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfflineStatus() {
        return offlineStatus;
    }

    /**
     * Sets the value of the offlineStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfflineStatus(String value) {
        this.offlineStatus = value;
    }

    /**
     * Gets the value of the paymentEntryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentEntryType() {
        return paymentEntryType;
    }

    /**
     * Sets the value of the paymentEntryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentEntryType(String value) {
        this.paymentEntryType = value;
    }

    /**
     * Gets the value of the processedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessedAmount() {
        return processedAmount;
    }

    /**
     * Sets the value of the processedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessedAmount(String value) {
        this.processedAmount = value;
    }

    /**
     * Gets the value of the reference1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference1() {
        return reference1;
    }

    /**
     * Sets the value of the reference1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference1(String value) {
        this.reference1 = value;
    }

    /**
     * Gets the value of the reference2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference2() {
        return reference2;
    }

    /**
     * Sets the value of the reference2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference2(String value) {
        this.reference2 = value;
    }

    /**
     * Gets the value of the requestAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestAmount() {
        return requestAmount;
    }

    /**
     * Sets the value of the requestAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestAmount(String value) {
        this.requestAmount = value;
    }

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestId(String value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the requestProcessed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestProcessed() {
        return requestProcessed;
    }

    /**
     * Sets the value of the requestProcessed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestProcessed(String value) {
        this.requestProcessed = value;
    }

    /**
     * Gets the value of the tranRequestTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranRequestTime() {
        return tranRequestTime;
    }

    /**
     * Sets the value of the tranRequestTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranRequestTime(String value) {
        this.tranRequestTime = value;
    }

    /**
     * Gets the value of the tranReturnCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranReturnCode() {
        return tranReturnCode;
    }

    /**
     * Sets the value of the tranReturnCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranReturnCode(String value) {
        this.tranReturnCode = value;
    }

    /**
     * Gets the value of the tranReturnFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranReturnFlag() {
        return tranReturnFlag;
    }

    /**
     * Sets the value of the tranReturnFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranReturnFlag(String value) {
        this.tranReturnFlag = value;
    }

    /**
     * Gets the value of the tranReturnMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranReturnMessage() {
        return tranReturnMessage;
    }

    /**
     * Sets the value of the tranReturnMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranReturnMessage(String value) {
        this.tranReturnMessage = value;
    }

    /**
     * Gets the value of the tranType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranType() {
        return tranType;
    }

    /**
     * Sets the value of the tranType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranType(String value) {
        this.tranType = value;
    }

    /**
     * Gets the value of the voidTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoidTransaction() {
        return voidTransaction;
    }

    /**
     * Sets the value of the voidTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoidTransaction(String value) {
        this.voidTransaction = value;
    }

    /**
     * Gets the value of the aDtype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aDtype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getADtype().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getADtype() {
        if (aDtype == null) {
            aDtype = new ArrayList<String>();
        }
        return this.aDtype;
    }

}
