//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.16 at 12:31:15 PM CDT 
//


package com.mozu.sterling.model.order;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "productLine",
    "serviceLine"
})
@XmlRootElement(name = "ProductServiceAssoc")
public class ProductServiceAssoc {

    @XmlElement(name = "ProductLine")
    protected ProductLine productLine;
    @XmlElement(name = "ServiceLine")
    protected ServiceLine serviceLine;

    /**
     * Gets the value of the productLine property.
     * 
     * @return
     *     possible object is
     *     {@link ProductLine }
     *     
     */
    public ProductLine getProductLine() {
        return productLine;
    }

    /**
     * Sets the value of the productLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductLine }
     *     
     */
    public void setProductLine(ProductLine value) {
        this.productLine = value;
    }

    /**
     * Gets the value of the serviceLine property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceLine }
     *     
     */
    public ServiceLine getServiceLine() {
        return serviceLine;
    }

    /**
     * Sets the value of the serviceLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceLine }
     *     
     */
    public void setServiceLine(ServiceLine value) {
        this.serviceLine = value;
    }

}
