//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.10 at 12:28:23 PM CST 
//


package com.mozu.sterling.model.shipment;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "DeliveryPlan")
public class DeliveryPlan {

    @XmlAttribute(name = "DeliveryPlanClosedFlag")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String deliveryPlanClosedFlag;
    @XmlAttribute(name = "DeliveryPlanDate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String deliveryPlanDate;
    @XmlAttribute(name = "DeliveryPlanKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String deliveryPlanKey;
    @XmlAttribute(name = "DeliveryPlanName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String deliveryPlanName;
    @XmlAttribute(name = "DeliveryPlanNo")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String deliveryPlanNo;
    @XmlAttribute(name = "DeliveryPlanPlannedFlag")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String deliveryPlanPlannedFlag;
    @XmlAttribute(name = "EnterpriseCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String enterpriseCode;
    @XmlAttribute(name = "OwnerOrganizationCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String ownerOrganizationCode;
    @XmlAttribute(name = "a-dtype")
    protected List<String> aDtype;

    /**
     * Gets the value of the deliveryPlanClosedFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryPlanClosedFlag() {
        return deliveryPlanClosedFlag;
    }

    /**
     * Sets the value of the deliveryPlanClosedFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryPlanClosedFlag(String value) {
        this.deliveryPlanClosedFlag = value;
    }

    /**
     * Gets the value of the deliveryPlanDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryPlanDate() {
        return deliveryPlanDate;
    }

    /**
     * Sets the value of the deliveryPlanDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryPlanDate(String value) {
        this.deliveryPlanDate = value;
    }

    /**
     * Gets the value of the deliveryPlanKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryPlanKey() {
        return deliveryPlanKey;
    }

    /**
     * Sets the value of the deliveryPlanKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryPlanKey(String value) {
        this.deliveryPlanKey = value;
    }

    /**
     * Gets the value of the deliveryPlanName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryPlanName() {
        return deliveryPlanName;
    }

    /**
     * Sets the value of the deliveryPlanName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryPlanName(String value) {
        this.deliveryPlanName = value;
    }

    /**
     * Gets the value of the deliveryPlanNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryPlanNo() {
        return deliveryPlanNo;
    }

    /**
     * Sets the value of the deliveryPlanNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryPlanNo(String value) {
        this.deliveryPlanNo = value;
    }

    /**
     * Gets the value of the deliveryPlanPlannedFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryPlanPlannedFlag() {
        return deliveryPlanPlannedFlag;
    }

    /**
     * Sets the value of the deliveryPlanPlannedFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryPlanPlannedFlag(String value) {
        this.deliveryPlanPlannedFlag = value;
    }

    /**
     * Gets the value of the enterpriseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnterpriseCode() {
        return enterpriseCode;
    }

    /**
     * Sets the value of the enterpriseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnterpriseCode(String value) {
        this.enterpriseCode = value;
    }

    /**
     * Gets the value of the ownerOrganizationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerOrganizationCode() {
        return ownerOrganizationCode;
    }

    /**
     * Sets the value of the ownerOrganizationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerOrganizationCode(String value) {
        this.ownerOrganizationCode = value;
    }

    /**
     * Gets the value of the aDtype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aDtype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getADtype().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getADtype() {
        if (aDtype == null) {
            aDtype = new ArrayList<String>();
        }
        return this.aDtype;
    }

}
