//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.10 at 12:28:23 PM CST 
//


package com.mozu.sterling.model.shipment;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "LinePriceInfo")
public class LinePriceInfo {

    @XmlAttribute(name = "ActualPricingQty")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String actualPricingQty;
    @XmlAttribute(name = "AdditionalLinePriceTotal")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String additionalLinePriceTotal;
    @XmlAttribute(name = "BundleTotal")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String bundleTotal;
    @XmlAttribute(name = "DiscountPercentage")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String discountPercentage;
    @XmlAttribute(name = "InvoicedLineTotal")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String invoicedLineTotal;
    @XmlAttribute(name = "InvoicedPricingQty")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String invoicedPricingQty;
    @XmlAttribute(name = "IsLinePriceForInformationOnly")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String isLinePriceForInformationOnly;
    @XmlAttribute(name = "IsPriceLocked")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String isPriceLocked;
    @XmlAttribute(name = "LineTotal")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lineTotal;
    @XmlAttribute(name = "ListPrice")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String listPrice;
    @XmlAttribute(name = "OrderedPricingQty")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String orderedPricingQty;
    @XmlAttribute(name = "PricingQtyConversionFactor")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pricingQtyConversionFactor;
    @XmlAttribute(name = "PricingUOM")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pricingUOM;
    @XmlAttribute(name = "RepricingQty")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String repricingQty;
    @XmlAttribute(name = "RetailPrice")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String retailPrice;
    @XmlAttribute(name = "SettledAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String settledAmount;
    @XmlAttribute(name = "SettledQuantity")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String settledQuantity;
    @XmlAttribute(name = "TaxExemptionCertificate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String taxExemptionCertificate;
    @XmlAttribute(name = "TaxableFlag")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String taxableFlag;
    @XmlAttribute(name = "UnitPrice")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String unitPrice;
    @XmlAttribute(name = "a-dtype")
    protected List<String> aDtype;

    /**
     * Gets the value of the actualPricingQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActualPricingQty() {
        return actualPricingQty;
    }

    /**
     * Sets the value of the actualPricingQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualPricingQty(String value) {
        this.actualPricingQty = value;
    }

    /**
     * Gets the value of the additionalLinePriceTotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalLinePriceTotal() {
        return additionalLinePriceTotal;
    }

    /**
     * Sets the value of the additionalLinePriceTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalLinePriceTotal(String value) {
        this.additionalLinePriceTotal = value;
    }

    /**
     * Gets the value of the bundleTotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBundleTotal() {
        return bundleTotal;
    }

    /**
     * Sets the value of the bundleTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBundleTotal(String value) {
        this.bundleTotal = value;
    }

    /**
     * Gets the value of the discountPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscountPercentage() {
        return discountPercentage;
    }

    /**
     * Sets the value of the discountPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscountPercentage(String value) {
        this.discountPercentage = value;
    }

    /**
     * Gets the value of the invoicedLineTotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoicedLineTotal() {
        return invoicedLineTotal;
    }

    /**
     * Sets the value of the invoicedLineTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoicedLineTotal(String value) {
        this.invoicedLineTotal = value;
    }

    /**
     * Gets the value of the invoicedPricingQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoicedPricingQty() {
        return invoicedPricingQty;
    }

    /**
     * Sets the value of the invoicedPricingQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoicedPricingQty(String value) {
        this.invoicedPricingQty = value;
    }

    /**
     * Gets the value of the isLinePriceForInformationOnly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsLinePriceForInformationOnly() {
        return isLinePriceForInformationOnly;
    }

    /**
     * Sets the value of the isLinePriceForInformationOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsLinePriceForInformationOnly(String value) {
        this.isLinePriceForInformationOnly = value;
    }

    /**
     * Gets the value of the isPriceLocked property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPriceLocked() {
        return isPriceLocked;
    }

    /**
     * Sets the value of the isPriceLocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPriceLocked(String value) {
        this.isPriceLocked = value;
    }

    /**
     * Gets the value of the lineTotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineTotal() {
        return lineTotal;
    }

    /**
     * Sets the value of the lineTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineTotal(String value) {
        this.lineTotal = value;
    }

    /**
     * Gets the value of the listPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListPrice() {
        return listPrice;
    }

    /**
     * Sets the value of the listPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListPrice(String value) {
        this.listPrice = value;
    }

    /**
     * Gets the value of the orderedPricingQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderedPricingQty() {
        return orderedPricingQty;
    }

    /**
     * Sets the value of the orderedPricingQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderedPricingQty(String value) {
        this.orderedPricingQty = value;
    }

    /**
     * Gets the value of the pricingQtyConversionFactor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPricingQtyConversionFactor() {
        return pricingQtyConversionFactor;
    }

    /**
     * Sets the value of the pricingQtyConversionFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPricingQtyConversionFactor(String value) {
        this.pricingQtyConversionFactor = value;
    }

    /**
     * Gets the value of the pricingUOM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPricingUOM() {
        return pricingUOM;
    }

    /**
     * Sets the value of the pricingUOM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPricingUOM(String value) {
        this.pricingUOM = value;
    }

    /**
     * Gets the value of the repricingQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepricingQty() {
        return repricingQty;
    }

    /**
     * Sets the value of the repricingQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepricingQty(String value) {
        this.repricingQty = value;
    }

    /**
     * Gets the value of the retailPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetailPrice() {
        return retailPrice;
    }

    /**
     * Sets the value of the retailPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetailPrice(String value) {
        this.retailPrice = value;
    }

    /**
     * Gets the value of the settledAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettledAmount() {
        return settledAmount;
    }

    /**
     * Sets the value of the settledAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettledAmount(String value) {
        this.settledAmount = value;
    }

    /**
     * Gets the value of the settledQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettledQuantity() {
        return settledQuantity;
    }

    /**
     * Sets the value of the settledQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettledQuantity(String value) {
        this.settledQuantity = value;
    }

    /**
     * Gets the value of the taxExemptionCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxExemptionCertificate() {
        return taxExemptionCertificate;
    }

    /**
     * Sets the value of the taxExemptionCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxExemptionCertificate(String value) {
        this.taxExemptionCertificate = value;
    }

    /**
     * Gets the value of the taxableFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxableFlag() {
        return taxableFlag;
    }

    /**
     * Sets the value of the taxableFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxableFlag(String value) {
        this.taxableFlag = value;
    }

    /**
     * Gets the value of the unitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitPrice() {
        return unitPrice;
    }

    /**
     * Sets the value of the unitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitPrice(String value) {
        this.unitPrice = value;
    }

    /**
     * Gets the value of the aDtype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aDtype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getADtype().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getADtype() {
        if (aDtype == null) {
            aDtype = new ArrayList<String>();
        }
        return this.aDtype;
    }

}
