//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.10 at 12:28:23 PM CST 
//


package com.mozu.sterling.model.shipment;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parentLine",
    "childLine"
})
@XmlRootElement(name = "OrderLineRelationship")
public class OrderLineRelationship {

    @XmlAttribute(name = "ChildOrderLineKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String childOrderLineKey;
    @XmlAttribute(name = "OrderHeaderKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String orderHeaderKey;
    @XmlAttribute(name = "OrderLineRelationshipKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String orderLineRelationshipKey;
    @XmlAttribute(name = "ParentOrderLineKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String parentOrderLineKey;
    @XmlAttribute(name = "RelationshipType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String relationshipType;
    @XmlElement(name = "ParentLine")
    protected ParentLine parentLine;
    @XmlElement(name = "ChildLine")
    protected ChildLine childLine;

    /**
     * Gets the value of the childOrderLineKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildOrderLineKey() {
        return childOrderLineKey;
    }

    /**
     * Sets the value of the childOrderLineKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildOrderLineKey(String value) {
        this.childOrderLineKey = value;
    }

    /**
     * Gets the value of the orderHeaderKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderHeaderKey() {
        return orderHeaderKey;
    }

    /**
     * Sets the value of the orderHeaderKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderHeaderKey(String value) {
        this.orderHeaderKey = value;
    }

    /**
     * Gets the value of the orderLineRelationshipKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderLineRelationshipKey() {
        return orderLineRelationshipKey;
    }

    /**
     * Sets the value of the orderLineRelationshipKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderLineRelationshipKey(String value) {
        this.orderLineRelationshipKey = value;
    }

    /**
     * Gets the value of the parentOrderLineKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentOrderLineKey() {
        return parentOrderLineKey;
    }

    /**
     * Sets the value of the parentOrderLineKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentOrderLineKey(String value) {
        this.parentOrderLineKey = value;
    }

    /**
     * Gets the value of the relationshipType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationshipType() {
        return relationshipType;
    }

    /**
     * Sets the value of the relationshipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationshipType(String value) {
        this.relationshipType = value;
    }

    /**
     * Gets the value of the parentLine property.
     * 
     * @return
     *     possible object is
     *     {@link ParentLine }
     *     
     */
    public ParentLine getParentLine() {
        return parentLine;
    }

    /**
     * Sets the value of the parentLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParentLine }
     *     
     */
    public void setParentLine(ParentLine value) {
        this.parentLine = value;
    }

    /**
     * Gets the value of the childLine property.
     * 
     * @return
     *     possible object is
     *     {@link ChildLine }
     *     
     */
    public ChildLine getChildLine() {
        return childLine;
    }

    /**
     * Sets the value of the childLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChildLine }
     *     
     */
    public void setChildLine(ChildLine value) {
        this.childLine = value;
    }

}
