//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.10 at 12:28:23 PM CST 
//


package com.mozu.sterling.model.shipment;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customAttributes"
})
@XmlRootElement(name = "OrderLineOption")
public class OrderLineOption {

    @XmlAttribute(name = "InvoicedOptionPrice")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String invoicedOptionPrice;
    @XmlAttribute(name = "InvoicedPricingQuantity")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String invoicedPricingQuantity;
    @XmlAttribute(name = "IsPriceLocked")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String isPriceLocked;
    @XmlAttribute(name = "OptionDescription")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String optionDescription;
    @XmlAttribute(name = "OptionItemID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String optionItemID;
    @XmlAttribute(name = "OptionPrice")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String optionPrice;
    @XmlAttribute(name = "OptionUOM")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String optionUOM;
    @XmlAttribute(name = "OrderLineOptionKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String orderLineOptionKey;
    @XmlAttribute(name = "PricingUOM")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pricingUOM;
    @XmlAttribute(name = "Quantity")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String quantity;
    @XmlAttribute(name = "UnitPrice")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String unitPrice;
    @XmlAttribute(name = "a-dtype")
    protected List<String> aDtype;
    @XmlElement(name = "CustomAttributes")
    protected CustomAttributes customAttributes;

    /**
     * Gets the value of the invoicedOptionPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoicedOptionPrice() {
        return invoicedOptionPrice;
    }

    /**
     * Sets the value of the invoicedOptionPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoicedOptionPrice(String value) {
        this.invoicedOptionPrice = value;
    }

    /**
     * Gets the value of the invoicedPricingQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoicedPricingQuantity() {
        return invoicedPricingQuantity;
    }

    /**
     * Sets the value of the invoicedPricingQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoicedPricingQuantity(String value) {
        this.invoicedPricingQuantity = value;
    }

    /**
     * Gets the value of the isPriceLocked property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPriceLocked() {
        return isPriceLocked;
    }

    /**
     * Sets the value of the isPriceLocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPriceLocked(String value) {
        this.isPriceLocked = value;
    }

    /**
     * Gets the value of the optionDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionDescription() {
        return optionDescription;
    }

    /**
     * Sets the value of the optionDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionDescription(String value) {
        this.optionDescription = value;
    }

    /**
     * Gets the value of the optionItemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionItemID() {
        return optionItemID;
    }

    /**
     * Sets the value of the optionItemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionItemID(String value) {
        this.optionItemID = value;
    }

    /**
     * Gets the value of the optionPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionPrice() {
        return optionPrice;
    }

    /**
     * Sets the value of the optionPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionPrice(String value) {
        this.optionPrice = value;
    }

    /**
     * Gets the value of the optionUOM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionUOM() {
        return optionUOM;
    }

    /**
     * Sets the value of the optionUOM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionUOM(String value) {
        this.optionUOM = value;
    }

    /**
     * Gets the value of the orderLineOptionKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderLineOptionKey() {
        return orderLineOptionKey;
    }

    /**
     * Sets the value of the orderLineOptionKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderLineOptionKey(String value) {
        this.orderLineOptionKey = value;
    }

    /**
     * Gets the value of the pricingUOM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPricingUOM() {
        return pricingUOM;
    }

    /**
     * Sets the value of the pricingUOM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPricingUOM(String value) {
        this.pricingUOM = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuantity(String value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the unitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitPrice() {
        return unitPrice;
    }

    /**
     * Sets the value of the unitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitPrice(String value) {
        this.unitPrice = value;
    }

    /**
     * Gets the value of the aDtype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aDtype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getADtype().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getADtype() {
        if (aDtype == null) {
            aDtype = new ArrayList<String>();
        }
        return this.aDtype;
    }

    /**
     * Gets the value of the customAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link CustomAttributes }
     *     
     */
    public CustomAttributes getCustomAttributes() {
        return customAttributes;
    }

    /**
     * Sets the value of the customAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomAttributes }
     *     
     */
    public void setCustomAttributes(CustomAttributes value) {
        this.customAttributes = value;
    }

}
