//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.10 at 12:28:23 PM CST 
//


package com.mozu.sterling.model.shipment;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bundleParentLine",
    "shipmentLineInvAttRequest",
    "shipmentTagSerials",
    "order",
    "orderLine",
    "orderRelease",
    "instructions",
    "department"
})
@XmlRootElement(name = "ShipmentLine")
public class ShipmentLine {

    @XmlAttribute(name = "ActualQuantity")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String actualQuantity;
    @XmlAttribute(name = "BackroomPickComplete")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String backroomPickComplete;
    @XmlAttribute(name = "BackroomPickedQuantity")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String backroomPickedQuantity;
    @XmlAttribute(name = "BuyerMarkForNodeId")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String buyerMarkForNodeId;
    @XmlAttribute(name = "CancelReason")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String cancelReason;
    @XmlAttribute(name = "ChainedFromOrderHeaderKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String chainedFromOrderHeaderKey;
    @XmlAttribute(name = "ChainedFromOrderLineKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String chainedFromOrderLineKey;
    @XmlAttribute(name = "CountryOfOrigin")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String countryOfOrigin;
    @XmlAttribute(name = "CustomerPickedQuantity")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String customerPickedQuantity;
    @XmlAttribute(name = "CustomerPoLineNo")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String customerPoLineNo;
    @XmlAttribute(name = "CustomerPoNo")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String customerPoNo;
    @XmlAttribute(name = "DocumentType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String documentType;
    @XmlAttribute(name = "ExternalReleaseIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String externalReleaseIdentifier;
    @XmlAttribute(name = "FifoNo")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String fifoNo;
    @XmlAttribute(name = "GroupSequenceNumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String groupSequenceNumber;
    @XmlAttribute(name = "IsCustomerPickComplete")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String isCustomerPickComplete;
    @XmlAttribute(name = "IsHazmat")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String isHazmat;
    @XmlAttribute(name = "IsPackComplete")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String isPackComplete;
    @XmlAttribute(name = "IsPickable")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String isPickable;
    @XmlAttribute(name = "ItemDesc")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String itemDesc;
    @XmlAttribute(name = "ItemID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String itemID;
    @XmlAttribute(name = "KitCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String kitCode;
    @XmlAttribute(name = "LevelOfService")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String levelOfService;
    @XmlAttribute(name = "NetWeight")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String netWeight;
    @XmlAttribute(name = "NetWeightUom")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String netWeightUom;
    @XmlAttribute(name = "OrderAvailableOnSystem")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String orderAvailableOnSystem;
    @XmlAttribute(name = "OrderHeaderKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String orderHeaderKey;
    @XmlAttribute(name = "OrderLineKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String orderLineKey;
    @XmlAttribute(name = "OrderNo")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String orderNo;
    @XmlAttribute(name = "OrderReleaseKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String orderReleaseKey;
    @XmlAttribute(name = "OverShipQuantity")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String overShipQuantity;
    @XmlAttribute(name = "PickLocation")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pickLocation;
    @XmlAttribute(name = "PickLocationSeq")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pickLocationSeq;
    @XmlAttribute(name = "PlacedQuantity")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String placedQuantity;
    @XmlAttribute(name = "PrimeLineNo")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String primeLineNo;
    @XmlAttribute(name = "ProductClass")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String productClass;
    @XmlAttribute(name = "Quantity")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String quantity;
    @XmlAttribute(name = "ReceivedQuantity")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String receivedQuantity;
    @XmlAttribute(name = "ReleaseNo")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String releaseNo;
    @XmlAttribute(name = "RequestedSerialNo")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String requestedSerialNo;
    @XmlAttribute(name = "ReturnShippingLabelLevel")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String returnShippingLabelLevel;
    @XmlAttribute(name = "Segment")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String segment;
    @XmlAttribute(name = "SegmentType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String segmentType;
    @XmlAttribute(name = "ShipToCustomerId")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String shipToCustomerId;
    @XmlAttribute(name = "ShipmentConsolidationGroupId")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String shipmentConsolidationGroupId;
    @XmlAttribute(name = "ShipmentKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String shipmentKey;
    @XmlAttribute(name = "ShipmentLineKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String shipmentLineKey;
    @XmlAttribute(name = "ShipmentLineNo")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String shipmentLineNo;
    @XmlAttribute(name = "ShipmentSubLineNo")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String shipmentSubLineNo;
    @XmlAttribute(name = "ShortageQty")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String shortageQty;
    @XmlAttribute(name = "ShortageResolutionReason")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String shortageResolutionReason;
    @XmlAttribute(name = "SubLineNo")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String subLineNo;
    @XmlAttribute(name = "UnitOfMeasure")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String unitOfMeasure;
    @XmlAttribute(name = "WaveNo")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String waveNo;
    @XmlAttribute(name = "isHistory")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String isHistory;
    @XmlAttribute(name = "a-dtype")
    protected List<String> aDtype;
    @XmlElement(name = "BundleParentLine")
    protected BundleParentLine bundleParentLine;
    @XmlElement(name = "ShipmentLineInvAttRequest")
    protected ShipmentLineInvAttRequest shipmentLineInvAttRequest;
    @XmlElement(name = "ShipmentTagSerials")
    protected ShipmentTagSerials shipmentTagSerials;
    @XmlElement(name = "Order")
    protected Order order;
    @XmlElement(name = "OrderLine")
    protected List<OrderLine> orderLine;
    @XmlElement(name = "OrderRelease")
    protected OrderRelease orderRelease;
    @XmlElement(name = "Instructions")
    protected Instructions instructions;
    @XmlElement(name = "Department")
    protected Department department;

    /**
     * Gets the value of the actualQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActualQuantity() {
        return actualQuantity;
    }

    /**
     * Sets the value of the actualQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualQuantity(String value) {
        this.actualQuantity = value;
    }

    /**
     * Gets the value of the backroomPickComplete property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackroomPickComplete() {
        return backroomPickComplete;
    }

    /**
     * Sets the value of the backroomPickComplete property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackroomPickComplete(String value) {
        this.backroomPickComplete = value;
    }

    /**
     * Gets the value of the backroomPickedQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackroomPickedQuantity() {
        return backroomPickedQuantity;
    }

    /**
     * Sets the value of the backroomPickedQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackroomPickedQuantity(String value) {
        this.backroomPickedQuantity = value;
    }

    /**
     * Gets the value of the buyerMarkForNodeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerMarkForNodeId() {
        return buyerMarkForNodeId;
    }

    /**
     * Sets the value of the buyerMarkForNodeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerMarkForNodeId(String value) {
        this.buyerMarkForNodeId = value;
    }

    /**
     * Gets the value of the cancelReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * Sets the value of the cancelReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelReason(String value) {
        this.cancelReason = value;
    }

    /**
     * Gets the value of the chainedFromOrderHeaderKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChainedFromOrderHeaderKey() {
        return chainedFromOrderHeaderKey;
    }

    /**
     * Sets the value of the chainedFromOrderHeaderKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChainedFromOrderHeaderKey(String value) {
        this.chainedFromOrderHeaderKey = value;
    }

    /**
     * Gets the value of the chainedFromOrderLineKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChainedFromOrderLineKey() {
        return chainedFromOrderLineKey;
    }

    /**
     * Sets the value of the chainedFromOrderLineKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChainedFromOrderLineKey(String value) {
        this.chainedFromOrderLineKey = value;
    }

    /**
     * Gets the value of the countryOfOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfOrigin() {
        return countryOfOrigin;
    }

    /**
     * Sets the value of the countryOfOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfOrigin(String value) {
        this.countryOfOrigin = value;
    }

    /**
     * Gets the value of the customerPickedQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerPickedQuantity() {
        return customerPickedQuantity;
    }

    /**
     * Sets the value of the customerPickedQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerPickedQuantity(String value) {
        this.customerPickedQuantity = value;
    }

    /**
     * Gets the value of the customerPoLineNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerPoLineNo() {
        return customerPoLineNo;
    }

    /**
     * Sets the value of the customerPoLineNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerPoLineNo(String value) {
        this.customerPoLineNo = value;
    }

    /**
     * Gets the value of the customerPoNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerPoNo() {
        return customerPoNo;
    }

    /**
     * Sets the value of the customerPoNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerPoNo(String value) {
        this.customerPoNo = value;
    }

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentType(String value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the externalReleaseIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalReleaseIdentifier() {
        return externalReleaseIdentifier;
    }

    /**
     * Sets the value of the externalReleaseIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalReleaseIdentifier(String value) {
        this.externalReleaseIdentifier = value;
    }

    /**
     * Gets the value of the fifoNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFifoNo() {
        return fifoNo;
    }

    /**
     * Sets the value of the fifoNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFifoNo(String value) {
        this.fifoNo = value;
    }

    /**
     * Gets the value of the groupSequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupSequenceNumber() {
        return groupSequenceNumber;
    }

    /**
     * Sets the value of the groupSequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupSequenceNumber(String value) {
        this.groupSequenceNumber = value;
    }

    /**
     * Gets the value of the isCustomerPickComplete property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsCustomerPickComplete() {
        return isCustomerPickComplete;
    }

    /**
     * Sets the value of the isCustomerPickComplete property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsCustomerPickComplete(String value) {
        this.isCustomerPickComplete = value;
    }

    /**
     * Gets the value of the isHazmat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsHazmat() {
        return isHazmat;
    }

    /**
     * Sets the value of the isHazmat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsHazmat(String value) {
        this.isHazmat = value;
    }

    /**
     * Gets the value of the isPackComplete property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPackComplete() {
        return isPackComplete;
    }

    /**
     * Sets the value of the isPackComplete property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPackComplete(String value) {
        this.isPackComplete = value;
    }

    /**
     * Gets the value of the isPickable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPickable() {
        return isPickable;
    }

    /**
     * Sets the value of the isPickable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPickable(String value) {
        this.isPickable = value;
    }

    /**
     * Gets the value of the itemDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemDesc() {
        return itemDesc;
    }

    /**
     * Sets the value of the itemDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemDesc(String value) {
        this.itemDesc = value;
    }

    /**
     * Gets the value of the itemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemID() {
        return itemID;
    }

    /**
     * Sets the value of the itemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemID(String value) {
        this.itemID = value;
    }

    /**
     * Gets the value of the kitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKitCode() {
        return kitCode;
    }

    /**
     * Sets the value of the kitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKitCode(String value) {
        this.kitCode = value;
    }

    /**
     * Gets the value of the levelOfService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevelOfService() {
        return levelOfService;
    }

    /**
     * Sets the value of the levelOfService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevelOfService(String value) {
        this.levelOfService = value;
    }

    /**
     * Gets the value of the netWeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetWeight() {
        return netWeight;
    }

    /**
     * Sets the value of the netWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetWeight(String value) {
        this.netWeight = value;
    }

    /**
     * Gets the value of the netWeightUom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetWeightUom() {
        return netWeightUom;
    }

    /**
     * Sets the value of the netWeightUom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetWeightUom(String value) {
        this.netWeightUom = value;
    }

    /**
     * Gets the value of the orderAvailableOnSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderAvailableOnSystem() {
        return orderAvailableOnSystem;
    }

    /**
     * Sets the value of the orderAvailableOnSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderAvailableOnSystem(String value) {
        this.orderAvailableOnSystem = value;
    }

    /**
     * Gets the value of the orderHeaderKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderHeaderKey() {
        return orderHeaderKey;
    }

    /**
     * Sets the value of the orderHeaderKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderHeaderKey(String value) {
        this.orderHeaderKey = value;
    }

    /**
     * Gets the value of the orderLineKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderLineKey() {
        return orderLineKey;
    }

    /**
     * Sets the value of the orderLineKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderLineKey(String value) {
        this.orderLineKey = value;
    }

    /**
     * Gets the value of the orderNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * Sets the value of the orderNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderNo(String value) {
        this.orderNo = value;
    }

    /**
     * Gets the value of the orderReleaseKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderReleaseKey() {
        return orderReleaseKey;
    }

    /**
     * Sets the value of the orderReleaseKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderReleaseKey(String value) {
        this.orderReleaseKey = value;
    }

    /**
     * Gets the value of the overShipQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverShipQuantity() {
        return overShipQuantity;
    }

    /**
     * Sets the value of the overShipQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverShipQuantity(String value) {
        this.overShipQuantity = value;
    }

    /**
     * Gets the value of the pickLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickLocation() {
        return pickLocation;
    }

    /**
     * Sets the value of the pickLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickLocation(String value) {
        this.pickLocation = value;
    }

    /**
     * Gets the value of the pickLocationSeq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickLocationSeq() {
        return pickLocationSeq;
    }

    /**
     * Sets the value of the pickLocationSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickLocationSeq(String value) {
        this.pickLocationSeq = value;
    }

    /**
     * Gets the value of the placedQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlacedQuantity() {
        return placedQuantity;
    }

    /**
     * Sets the value of the placedQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlacedQuantity(String value) {
        this.placedQuantity = value;
    }

    /**
     * Gets the value of the primeLineNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimeLineNo() {
        return primeLineNo;
    }

    /**
     * Sets the value of the primeLineNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimeLineNo(String value) {
        this.primeLineNo = value;
    }

    /**
     * Gets the value of the productClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductClass() {
        return productClass;
    }

    /**
     * Sets the value of the productClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductClass(String value) {
        this.productClass = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuantity(String value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the receivedQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceivedQuantity() {
        return receivedQuantity;
    }

    /**
     * Sets the value of the receivedQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceivedQuantity(String value) {
        this.receivedQuantity = value;
    }

    /**
     * Gets the value of the releaseNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReleaseNo() {
        return releaseNo;
    }

    /**
     * Sets the value of the releaseNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReleaseNo(String value) {
        this.releaseNo = value;
    }

    /**
     * Gets the value of the requestedSerialNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestedSerialNo() {
        return requestedSerialNo;
    }

    /**
     * Sets the value of the requestedSerialNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestedSerialNo(String value) {
        this.requestedSerialNo = value;
    }

    /**
     * Gets the value of the returnShippingLabelLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnShippingLabelLevel() {
        return returnShippingLabelLevel;
    }

    /**
     * Sets the value of the returnShippingLabelLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnShippingLabelLevel(String value) {
        this.returnShippingLabelLevel = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment(String value) {
        this.segment = value;
    }

    /**
     * Gets the value of the segmentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegmentType() {
        return segmentType;
    }

    /**
     * Sets the value of the segmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegmentType(String value) {
        this.segmentType = value;
    }

    /**
     * Gets the value of the shipToCustomerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipToCustomerId() {
        return shipToCustomerId;
    }

    /**
     * Sets the value of the shipToCustomerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipToCustomerId(String value) {
        this.shipToCustomerId = value;
    }

    /**
     * Gets the value of the shipmentConsolidationGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentConsolidationGroupId() {
        return shipmentConsolidationGroupId;
    }

    /**
     * Sets the value of the shipmentConsolidationGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentConsolidationGroupId(String value) {
        this.shipmentConsolidationGroupId = value;
    }

    /**
     * Gets the value of the shipmentKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentKey() {
        return shipmentKey;
    }

    /**
     * Sets the value of the shipmentKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentKey(String value) {
        this.shipmentKey = value;
    }

    /**
     * Gets the value of the shipmentLineKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentLineKey() {
        return shipmentLineKey;
    }

    /**
     * Sets the value of the shipmentLineKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentLineKey(String value) {
        this.shipmentLineKey = value;
    }

    /**
     * Gets the value of the shipmentLineNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentLineNo() {
        return shipmentLineNo;
    }

    /**
     * Sets the value of the shipmentLineNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentLineNo(String value) {
        this.shipmentLineNo = value;
    }

    /**
     * Gets the value of the shipmentSubLineNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentSubLineNo() {
        return shipmentSubLineNo;
    }

    /**
     * Sets the value of the shipmentSubLineNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentSubLineNo(String value) {
        this.shipmentSubLineNo = value;
    }

    /**
     * Gets the value of the shortageQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortageQty() {
        return shortageQty;
    }

    /**
     * Sets the value of the shortageQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortageQty(String value) {
        this.shortageQty = value;
    }

    /**
     * Gets the value of the shortageResolutionReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortageResolutionReason() {
        return shortageResolutionReason;
    }

    /**
     * Sets the value of the shortageResolutionReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortageResolutionReason(String value) {
        this.shortageResolutionReason = value;
    }

    /**
     * Gets the value of the subLineNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubLineNo() {
        return subLineNo;
    }

    /**
     * Sets the value of the subLineNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubLineNo(String value) {
        this.subLineNo = value;
    }

    /**
     * Gets the value of the unitOfMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitOfMeasure() {
        return unitOfMeasure;
    }

    /**
     * Sets the value of the unitOfMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitOfMeasure(String value) {
        this.unitOfMeasure = value;
    }

    /**
     * Gets the value of the waveNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaveNo() {
        return waveNo;
    }

    /**
     * Sets the value of the waveNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaveNo(String value) {
        this.waveNo = value;
    }

    /**
     * Gets the value of the isHistory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsHistory() {
        return isHistory;
    }

    /**
     * Sets the value of the isHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsHistory(String value) {
        this.isHistory = value;
    }

    /**
     * Gets the value of the aDtype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aDtype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getADtype().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getADtype() {
        if (aDtype == null) {
            aDtype = new ArrayList<String>();
        }
        return this.aDtype;
    }

    /**
     * Gets the value of the bundleParentLine property.
     * 
     * @return
     *     possible object is
     *     {@link BundleParentLine }
     *     
     */
    public BundleParentLine getBundleParentLine() {
        return bundleParentLine;
    }

    /**
     * Sets the value of the bundleParentLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link BundleParentLine }
     *     
     */
    public void setBundleParentLine(BundleParentLine value) {
        this.bundleParentLine = value;
    }

    /**
     * Gets the value of the shipmentLineInvAttRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentLineInvAttRequest }
     *     
     */
    public ShipmentLineInvAttRequest getShipmentLineInvAttRequest() {
        return shipmentLineInvAttRequest;
    }

    /**
     * Sets the value of the shipmentLineInvAttRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentLineInvAttRequest }
     *     
     */
    public void setShipmentLineInvAttRequest(ShipmentLineInvAttRequest value) {
        this.shipmentLineInvAttRequest = value;
    }

    /**
     * Gets the value of the shipmentTagSerials property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentTagSerials }
     *     
     */
    public ShipmentTagSerials getShipmentTagSerials() {
        return shipmentTagSerials;
    }

    /**
     * Sets the value of the shipmentTagSerials property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentTagSerials }
     *     
     */
    public void setShipmentTagSerials(ShipmentTagSerials value) {
        this.shipmentTagSerials = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link Order }
     *     
     */
    public Order getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link Order }
     *     
     */
    public void setOrder(Order value) {
        this.order = value;
    }

    /**
     * Gets the value of the orderLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderLine }
     * 
     * 
     */
    public List<OrderLine> getOrderLine() {
        if (orderLine == null) {
            orderLine = new ArrayList<OrderLine>();
        }
        return this.orderLine;
    }

    /**
     * Gets the value of the orderRelease property.
     * 
     * @return
     *     possible object is
     *     {@link OrderRelease }
     *     
     */
    public OrderRelease getOrderRelease() {
        return orderRelease;
    }

    /**
     * Sets the value of the orderRelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderRelease }
     *     
     */
    public void setOrderRelease(OrderRelease value) {
        this.orderRelease = value;
    }

    /**
     * Gets the value of the instructions property.
     * 
     * @return
     *     possible object is
     *     {@link Instructions }
     *     
     */
    public Instructions getInstructions() {
        return instructions;
    }

    /**
     * Sets the value of the instructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Instructions }
     *     
     */
    public void setInstructions(Instructions value) {
        this.instructions = value;
    }

    /**
     * Gets the value of the department property.
     * 
     * @return
     *     possible object is
     *     {@link Department }
     *     
     */
    public Department getDepartment() {
        return department;
    }

    /**
     * Sets the value of the department property.
     * 
     * @param value
     *     allowed object is
     *     {@link Department }
     *     
     */
    public void setDepartment(Department value) {
        this.department = value;
    }

}
