//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.04 at 09:40:37 AM CST 
//


package com.mozu.sterling.model.organization;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "corporatePersonInfo",
    "contactPersonInfo",
    "billingPersonInfo",
    "orgProtocolList",
    "orgRelationshipList",
    "userList",
    "relatedOrgList",
    "enterpriseOrgList",
    "userGroups",
    "enterprise",
    "orgDocumentList",
    "departmentList",
    "node",
    "carrierAttributes",
    "paymentRuleList",
    "paymentTypeList",
    "orgRoleList",
    "orgServiceList",
    "buyerInstructions",
    "orgThemeList",
    "enterpriseCostPurposes",
    "sellerCostPurposes"
})
@XmlRootElement(name = "Organization")
public class Organization {

    @XmlAttribute(name = "AccountWithHub")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String accountWithHub;
    @XmlAttribute(name = "AuthorityType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String authorityType;
    @XmlAttribute(name = "BillingAddressKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String billingAddressKey;
    @XmlAttribute(name = "BusinessCalendarKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String businessCalendarKey;
    @XmlAttribute(name = "CapacityOrganizationCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String capacityOrganizationCode;
    @XmlAttribute(name = "CatalogOrganizationCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String catalogOrganizationCode;
    @XmlAttribute(name = "ContactAddressKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String contactAddressKey;
    @XmlAttribute(name = "CorporateAddressKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String corporateAddressKey;
    @XmlAttribute(name = "CreatorOrganizationKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String creatorOrganizationKey;
    @XmlAttribute(name = "CustomerMaintainedExternally")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String customerMaintainedExternally;
    @XmlAttribute(name = "CustomerMasterOrganizationCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String customerMasterOrganizationCode;
    @XmlAttribute(name = "DefaultDistributionRuleId")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String defaultDistributionRuleId;
    @XmlAttribute(name = "DefaultPaymentRuleId")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String defaultPaymentRuleId;
    @XmlAttribute(name = "DefaultPriceProgramKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String defaultPriceProgramKey;
    @XmlAttribute(name = "DunsNumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String dunsNumber;
    @XmlAttribute(name = "InheritConfigFromEnterprise")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String inheritConfigFromEnterprise;
    @XmlAttribute(name = "InventoryKeptExternally")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String inventoryKeptExternally;
    @XmlAttribute(name = "InventoryOrganizationCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String inventoryOrganizationCode;
    @XmlAttribute(name = "InventoryPublished")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String inventoryPublished;
    @XmlAttribute(name = "IsEnterprise")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String isEnterprise;
    @XmlAttribute(name = "IsHubOrganization")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String isHubOrganization;
    @XmlAttribute(name = "IsLegalEntity")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String isLegalEntity;
    @XmlAttribute(name = "IsNode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String isNode;
    @XmlAttribute(name = "IsSeller")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String isSeller;
    @XmlAttribute(name = "IsSourcingKept")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String isSourcingKept;
    @XmlAttribute(name = "IsTemplate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String isTemplate;
    @XmlAttribute(name = "IssuingAuthority")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String issuingAuthority;
    @XmlAttribute(name = "ItemXrefRule")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String itemXrefRule;
    @XmlAttribute(name = "LocaleCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String localeCode;
    @XmlAttribute(name = "NumberOfChildren")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String numberOfChildren;
    @XmlAttribute(name = "OrganizationCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String organizationCode;
    @XmlAttribute(name = "OrganizationKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String organizationKey;
    @XmlAttribute(name = "OrganizationName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String organizationName;
    @XmlAttribute(name = "OrganizationSuffix")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String organizationSuffix;
    @XmlAttribute(name = "ParentOrganizationCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String parentOrganizationCode;
    @XmlAttribute(name = "PasswordPolicyKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String passwordPolicyKey;
    @XmlAttribute(name = "PaymentProcessingReqd")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String paymentProcessingReqd;
    @XmlAttribute(name = "PrimaryEnterpriseKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String primaryEnterpriseKey;
    @XmlAttribute(name = "PrimarySicCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String primarySicCode;
    @XmlAttribute(name = "PrimaryUrl")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String primaryUrl;
    @XmlAttribute(name = "RequiresChainedOrder")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String requiresChainedOrder;
    @XmlAttribute(name = "RequiresChangeRequest")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String requiresChangeRequest;
    @XmlAttribute(name = "ResourceIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String resourceIdentifier;
    @XmlAttribute(name = "StoreConfigOrganizationCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String storeConfigOrganizationCode;
    @XmlAttribute(name = "SupplyKeptExternally")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String supplyKeptExternally;
    @XmlAttribute(name = "TaxExemptFlag")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String taxExemptFlag;
    @XmlAttribute(name = "TaxExemptionCertificate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String taxExemptionCertificate;
    @XmlAttribute(name = "TaxJurisdiction")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String taxJurisdiction;
    @XmlAttribute(name = "TaxpayerId")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String taxpayerId;
    @XmlAttribute(name = "XrefAliasType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String xrefAliasType;
    @XmlAttribute(name = "XrefOrganizationCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String xrefOrganizationCode;
    @XmlAttribute(name = "a-dtype")
    protected List<String> aDtype;
    @XmlElement(name = "CorporatePersonInfo")
    protected CorporatePersonInfo corporatePersonInfo;
    @XmlElement(name = "ContactPersonInfo")
    protected ContactPersonInfo contactPersonInfo;
    @XmlElement(name = "BillingPersonInfo")
    protected BillingPersonInfo billingPersonInfo;
    @XmlElement(name = "OrgProtocolList")
    protected OrgProtocolList orgProtocolList;
    @XmlElement(name = "OrgRelationshipList")
    protected OrgRelationshipList orgRelationshipList;
    @XmlElement(name = "UserList")
    protected UserList userList;
    @XmlElement(name = "RelatedOrgList")
    protected RelatedOrgList relatedOrgList;
    @XmlElement(name = "EnterpriseOrgList")
    protected EnterpriseOrgList enterpriseOrgList;
    @XmlElement(name = "UserGroups")
    protected UserGroups userGroups;
    @XmlElement(name = "Enterprise")
    protected Enterprise enterprise;
    @XmlElement(name = "OrgDocumentList")
    protected OrgDocumentList orgDocumentList;
    @XmlElement(name = "DepartmentList")
    protected DepartmentList departmentList;
    @XmlElement(name = "Node")
    protected Node node;
    @XmlElement(name = "CarrierAttributes")
    protected CarrierAttributes carrierAttributes;
    @XmlElement(name = "PaymentRuleList")
    protected PaymentRuleList paymentRuleList;
    @XmlElement(name = "PaymentTypeList")
    protected PaymentTypeList paymentTypeList;
    @XmlElement(name = "OrgRoleList")
    protected OrgRoleList orgRoleList;
    @XmlElement(name = "OrgServiceList")
    protected OrgServiceList orgServiceList;
    @XmlElement(name = "BuyerInstructions")
    protected BuyerInstructions buyerInstructions;
    @XmlElement(name = "OrgThemeList")
    protected OrgThemeList orgThemeList;
    @XmlElement(name = "EnterpriseCostPurposes")
    protected EnterpriseCostPurposes enterpriseCostPurposes;
    @XmlElement(name = "SellerCostPurposes")
    protected SellerCostPurposes sellerCostPurposes;

    /**
     * Gets the value of the accountWithHub property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountWithHub() {
        return accountWithHub;
    }

    /**
     * Sets the value of the accountWithHub property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountWithHub(String value) {
        this.accountWithHub = value;
    }

    /**
     * Gets the value of the authorityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorityType() {
        return authorityType;
    }

    /**
     * Sets the value of the authorityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorityType(String value) {
        this.authorityType = value;
    }

    /**
     * Gets the value of the billingAddressKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingAddressKey() {
        return billingAddressKey;
    }

    /**
     * Sets the value of the billingAddressKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingAddressKey(String value) {
        this.billingAddressKey = value;
    }

    /**
     * Gets the value of the businessCalendarKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessCalendarKey() {
        return businessCalendarKey;
    }

    /**
     * Sets the value of the businessCalendarKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessCalendarKey(String value) {
        this.businessCalendarKey = value;
    }

    /**
     * Gets the value of the capacityOrganizationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapacityOrganizationCode() {
        return capacityOrganizationCode;
    }

    /**
     * Sets the value of the capacityOrganizationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapacityOrganizationCode(String value) {
        this.capacityOrganizationCode = value;
    }

    /**
     * Gets the value of the catalogOrganizationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalogOrganizationCode() {
        return catalogOrganizationCode;
    }

    /**
     * Sets the value of the catalogOrganizationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalogOrganizationCode(String value) {
        this.catalogOrganizationCode = value;
    }

    /**
     * Gets the value of the contactAddressKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactAddressKey() {
        return contactAddressKey;
    }

    /**
     * Sets the value of the contactAddressKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactAddressKey(String value) {
        this.contactAddressKey = value;
    }

    /**
     * Gets the value of the corporateAddressKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorporateAddressKey() {
        return corporateAddressKey;
    }

    /**
     * Sets the value of the corporateAddressKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorporateAddressKey(String value) {
        this.corporateAddressKey = value;
    }

    /**
     * Gets the value of the creatorOrganizationKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatorOrganizationKey() {
        return creatorOrganizationKey;
    }

    /**
     * Sets the value of the creatorOrganizationKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatorOrganizationKey(String value) {
        this.creatorOrganizationKey = value;
    }

    /**
     * Gets the value of the customerMaintainedExternally property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerMaintainedExternally() {
        return customerMaintainedExternally;
    }

    /**
     * Sets the value of the customerMaintainedExternally property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerMaintainedExternally(String value) {
        this.customerMaintainedExternally = value;
    }

    /**
     * Gets the value of the customerMasterOrganizationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerMasterOrganizationCode() {
        return customerMasterOrganizationCode;
    }

    /**
     * Sets the value of the customerMasterOrganizationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerMasterOrganizationCode(String value) {
        this.customerMasterOrganizationCode = value;
    }

    /**
     * Gets the value of the defaultDistributionRuleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultDistributionRuleId() {
        return defaultDistributionRuleId;
    }

    /**
     * Sets the value of the defaultDistributionRuleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultDistributionRuleId(String value) {
        this.defaultDistributionRuleId = value;
    }

    /**
     * Gets the value of the defaultPaymentRuleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultPaymentRuleId() {
        return defaultPaymentRuleId;
    }

    /**
     * Sets the value of the defaultPaymentRuleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultPaymentRuleId(String value) {
        this.defaultPaymentRuleId = value;
    }

    /**
     * Gets the value of the defaultPriceProgramKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultPriceProgramKey() {
        return defaultPriceProgramKey;
    }

    /**
     * Sets the value of the defaultPriceProgramKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultPriceProgramKey(String value) {
        this.defaultPriceProgramKey = value;
    }

    /**
     * Gets the value of the dunsNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDunsNumber() {
        return dunsNumber;
    }

    /**
     * Sets the value of the dunsNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDunsNumber(String value) {
        this.dunsNumber = value;
    }

    /**
     * Gets the value of the inheritConfigFromEnterprise property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInheritConfigFromEnterprise() {
        return inheritConfigFromEnterprise;
    }

    /**
     * Sets the value of the inheritConfigFromEnterprise property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInheritConfigFromEnterprise(String value) {
        this.inheritConfigFromEnterprise = value;
    }

    /**
     * Gets the value of the inventoryKeptExternally property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventoryKeptExternally() {
        return inventoryKeptExternally;
    }

    /**
     * Sets the value of the inventoryKeptExternally property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventoryKeptExternally(String value) {
        this.inventoryKeptExternally = value;
    }

    /**
     * Gets the value of the inventoryOrganizationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventoryOrganizationCode() {
        return inventoryOrganizationCode;
    }

    /**
     * Sets the value of the inventoryOrganizationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventoryOrganizationCode(String value) {
        this.inventoryOrganizationCode = value;
    }

    /**
     * Gets the value of the inventoryPublished property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventoryPublished() {
        return inventoryPublished;
    }

    /**
     * Sets the value of the inventoryPublished property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventoryPublished(String value) {
        this.inventoryPublished = value;
    }

    /**
     * Gets the value of the isEnterprise property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsEnterprise() {
        return isEnterprise;
    }

    /**
     * Sets the value of the isEnterprise property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsEnterprise(String value) {
        this.isEnterprise = value;
    }

    /**
     * Gets the value of the isHubOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsHubOrganization() {
        return isHubOrganization;
    }

    /**
     * Sets the value of the isHubOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsHubOrganization(String value) {
        this.isHubOrganization = value;
    }

    /**
     * Gets the value of the isLegalEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsLegalEntity() {
        return isLegalEntity;
    }

    /**
     * Sets the value of the isLegalEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsLegalEntity(String value) {
        this.isLegalEntity = value;
    }

    /**
     * Gets the value of the isNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsNode() {
        return isNode;
    }

    /**
     * Sets the value of the isNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsNode(String value) {
        this.isNode = value;
    }

    /**
     * Gets the value of the isSeller property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsSeller() {
        return isSeller;
    }

    /**
     * Sets the value of the isSeller property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsSeller(String value) {
        this.isSeller = value;
    }

    /**
     * Gets the value of the isSourcingKept property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsSourcingKept() {
        return isSourcingKept;
    }

    /**
     * Sets the value of the isSourcingKept property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsSourcingKept(String value) {
        this.isSourcingKept = value;
    }

    /**
     * Gets the value of the isTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsTemplate() {
        return isTemplate;
    }

    /**
     * Sets the value of the isTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsTemplate(String value) {
        this.isTemplate = value;
    }

    /**
     * Gets the value of the issuingAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuingAuthority() {
        return issuingAuthority;
    }

    /**
     * Sets the value of the issuingAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuingAuthority(String value) {
        this.issuingAuthority = value;
    }

    /**
     * Gets the value of the itemXrefRule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemXrefRule() {
        return itemXrefRule;
    }

    /**
     * Sets the value of the itemXrefRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemXrefRule(String value) {
        this.itemXrefRule = value;
    }

    /**
     * Gets the value of the localeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocaleCode() {
        return localeCode;
    }

    /**
     * Sets the value of the localeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocaleCode(String value) {
        this.localeCode = value;
    }

    /**
     * Gets the value of the numberOfChildren property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfChildren() {
        return numberOfChildren;
    }

    /**
     * Sets the value of the numberOfChildren property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfChildren(String value) {
        this.numberOfChildren = value;
    }

    /**
     * Gets the value of the organizationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationCode() {
        return organizationCode;
    }

    /**
     * Sets the value of the organizationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationCode(String value) {
        this.organizationCode = value;
    }

    /**
     * Gets the value of the organizationKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationKey() {
        return organizationKey;
    }

    /**
     * Sets the value of the organizationKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationKey(String value) {
        this.organizationKey = value;
    }

    /**
     * Gets the value of the organizationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationName() {
        return organizationName;
    }

    /**
     * Sets the value of the organizationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationName(String value) {
        this.organizationName = value;
    }

    /**
     * Gets the value of the organizationSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationSuffix() {
        return organizationSuffix;
    }

    /**
     * Sets the value of the organizationSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationSuffix(String value) {
        this.organizationSuffix = value;
    }

    /**
     * Gets the value of the parentOrganizationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentOrganizationCode() {
        return parentOrganizationCode;
    }

    /**
     * Sets the value of the parentOrganizationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentOrganizationCode(String value) {
        this.parentOrganizationCode = value;
    }

    /**
     * Gets the value of the passwordPolicyKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasswordPolicyKey() {
        return passwordPolicyKey;
    }

    /**
     * Sets the value of the passwordPolicyKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasswordPolicyKey(String value) {
        this.passwordPolicyKey = value;
    }

    /**
     * Gets the value of the paymentProcessingReqd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentProcessingReqd() {
        return paymentProcessingReqd;
    }

    /**
     * Sets the value of the paymentProcessingReqd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentProcessingReqd(String value) {
        this.paymentProcessingReqd = value;
    }

    /**
     * Gets the value of the primaryEnterpriseKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryEnterpriseKey() {
        return primaryEnterpriseKey;
    }

    /**
     * Sets the value of the primaryEnterpriseKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryEnterpriseKey(String value) {
        this.primaryEnterpriseKey = value;
    }

    /**
     * Gets the value of the primarySicCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimarySicCode() {
        return primarySicCode;
    }

    /**
     * Sets the value of the primarySicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimarySicCode(String value) {
        this.primarySicCode = value;
    }

    /**
     * Gets the value of the primaryUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryUrl() {
        return primaryUrl;
    }

    /**
     * Sets the value of the primaryUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryUrl(String value) {
        this.primaryUrl = value;
    }

    /**
     * Gets the value of the requiresChainedOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequiresChainedOrder() {
        return requiresChainedOrder;
    }

    /**
     * Sets the value of the requiresChainedOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequiresChainedOrder(String value) {
        this.requiresChainedOrder = value;
    }

    /**
     * Gets the value of the requiresChangeRequest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequiresChangeRequest() {
        return requiresChangeRequest;
    }

    /**
     * Sets the value of the requiresChangeRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequiresChangeRequest(String value) {
        this.requiresChangeRequest = value;
    }

    /**
     * Gets the value of the resourceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceIdentifier() {
        return resourceIdentifier;
    }

    /**
     * Sets the value of the resourceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceIdentifier(String value) {
        this.resourceIdentifier = value;
    }

    /**
     * Gets the value of the storeConfigOrganizationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoreConfigOrganizationCode() {
        return storeConfigOrganizationCode;
    }

    /**
     * Sets the value of the storeConfigOrganizationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoreConfigOrganizationCode(String value) {
        this.storeConfigOrganizationCode = value;
    }

    /**
     * Gets the value of the supplyKeptExternally property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplyKeptExternally() {
        return supplyKeptExternally;
    }

    /**
     * Sets the value of the supplyKeptExternally property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplyKeptExternally(String value) {
        this.supplyKeptExternally = value;
    }

    /**
     * Gets the value of the taxExemptFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxExemptFlag() {
        return taxExemptFlag;
    }

    /**
     * Sets the value of the taxExemptFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxExemptFlag(String value) {
        this.taxExemptFlag = value;
    }

    /**
     * Gets the value of the taxExemptionCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxExemptionCertificate() {
        return taxExemptionCertificate;
    }

    /**
     * Sets the value of the taxExemptionCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxExemptionCertificate(String value) {
        this.taxExemptionCertificate = value;
    }

    /**
     * Gets the value of the taxJurisdiction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxJurisdiction() {
        return taxJurisdiction;
    }

    /**
     * Sets the value of the taxJurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxJurisdiction(String value) {
        this.taxJurisdiction = value;
    }

    /**
     * Gets the value of the taxpayerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxpayerId() {
        return taxpayerId;
    }

    /**
     * Sets the value of the taxpayerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxpayerId(String value) {
        this.taxpayerId = value;
    }

    /**
     * Gets the value of the xrefAliasType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXrefAliasType() {
        return xrefAliasType;
    }

    /**
     * Sets the value of the xrefAliasType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXrefAliasType(String value) {
        this.xrefAliasType = value;
    }

    /**
     * Gets the value of the xrefOrganizationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXrefOrganizationCode() {
        return xrefOrganizationCode;
    }

    /**
     * Sets the value of the xrefOrganizationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXrefOrganizationCode(String value) {
        this.xrefOrganizationCode = value;
    }

    /**
     * Gets the value of the aDtype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aDtype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getADtype().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getADtype() {
        if (aDtype == null) {
            aDtype = new ArrayList<String>();
        }
        return this.aDtype;
    }

    /**
     * Gets the value of the corporatePersonInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CorporatePersonInfo }
     *     
     */
    public CorporatePersonInfo getCorporatePersonInfo() {
        return corporatePersonInfo;
    }

    /**
     * Sets the value of the corporatePersonInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorporatePersonInfo }
     *     
     */
    public void setCorporatePersonInfo(CorporatePersonInfo value) {
        this.corporatePersonInfo = value;
    }

    /**
     * Gets the value of the contactPersonInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ContactPersonInfo }
     *     
     */
    public ContactPersonInfo getContactPersonInfo() {
        return contactPersonInfo;
    }

    /**
     * Sets the value of the contactPersonInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactPersonInfo }
     *     
     */
    public void setContactPersonInfo(ContactPersonInfo value) {
        this.contactPersonInfo = value;
    }

    /**
     * Gets the value of the billingPersonInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BillingPersonInfo }
     *     
     */
    public BillingPersonInfo getBillingPersonInfo() {
        return billingPersonInfo;
    }

    /**
     * Sets the value of the billingPersonInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillingPersonInfo }
     *     
     */
    public void setBillingPersonInfo(BillingPersonInfo value) {
        this.billingPersonInfo = value;
    }

    /**
     * Gets the value of the orgProtocolList property.
     * 
     * @return
     *     possible object is
     *     {@link OrgProtocolList }
     *     
     */
    public OrgProtocolList getOrgProtocolList() {
        return orgProtocolList;
    }

    /**
     * Sets the value of the orgProtocolList property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgProtocolList }
     *     
     */
    public void setOrgProtocolList(OrgProtocolList value) {
        this.orgProtocolList = value;
    }

    /**
     * Gets the value of the orgRelationshipList property.
     * 
     * @return
     *     possible object is
     *     {@link OrgRelationshipList }
     *     
     */
    public OrgRelationshipList getOrgRelationshipList() {
        return orgRelationshipList;
    }

    /**
     * Sets the value of the orgRelationshipList property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgRelationshipList }
     *     
     */
    public void setOrgRelationshipList(OrgRelationshipList value) {
        this.orgRelationshipList = value;
    }

    /**
     * Gets the value of the userList property.
     * 
     * @return
     *     possible object is
     *     {@link UserList }
     *     
     */
    public UserList getUserList() {
        return userList;
    }

    /**
     * Sets the value of the userList property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserList }
     *     
     */
    public void setUserList(UserList value) {
        this.userList = value;
    }

    /**
     * Gets the value of the relatedOrgList property.
     * 
     * @return
     *     possible object is
     *     {@link RelatedOrgList }
     *     
     */
    public RelatedOrgList getRelatedOrgList() {
        return relatedOrgList;
    }

    /**
     * Sets the value of the relatedOrgList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelatedOrgList }
     *     
     */
    public void setRelatedOrgList(RelatedOrgList value) {
        this.relatedOrgList = value;
    }

    /**
     * Gets the value of the enterpriseOrgList property.
     * 
     * @return
     *     possible object is
     *     {@link EnterpriseOrgList }
     *     
     */
    public EnterpriseOrgList getEnterpriseOrgList() {
        return enterpriseOrgList;
    }

    /**
     * Sets the value of the enterpriseOrgList property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnterpriseOrgList }
     *     
     */
    public void setEnterpriseOrgList(EnterpriseOrgList value) {
        this.enterpriseOrgList = value;
    }

    /**
     * Gets the value of the userGroups property.
     * 
     * @return
     *     possible object is
     *     {@link UserGroups }
     *     
     */
    public UserGroups getUserGroups() {
        return userGroups;
    }

    /**
     * Sets the value of the userGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserGroups }
     *     
     */
    public void setUserGroups(UserGroups value) {
        this.userGroups = value;
    }

    /**
     * Gets the value of the enterprise property.
     * 
     * @return
     *     possible object is
     *     {@link Enterprise }
     *     
     */
    public Enterprise getEnterprise() {
        return enterprise;
    }

    /**
     * Sets the value of the enterprise property.
     * 
     * @param value
     *     allowed object is
     *     {@link Enterprise }
     *     
     */
    public void setEnterprise(Enterprise value) {
        this.enterprise = value;
    }

    /**
     * Gets the value of the orgDocumentList property.
     * 
     * @return
     *     possible object is
     *     {@link OrgDocumentList }
     *     
     */
    public OrgDocumentList getOrgDocumentList() {
        return orgDocumentList;
    }

    /**
     * Sets the value of the orgDocumentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgDocumentList }
     *     
     */
    public void setOrgDocumentList(OrgDocumentList value) {
        this.orgDocumentList = value;
    }

    /**
     * Gets the value of the departmentList property.
     * 
     * @return
     *     possible object is
     *     {@link DepartmentList }
     *     
     */
    public DepartmentList getDepartmentList() {
        return departmentList;
    }

    /**
     * Sets the value of the departmentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DepartmentList }
     *     
     */
    public void setDepartmentList(DepartmentList value) {
        this.departmentList = value;
    }

    /**
     * Gets the value of the node property.
     * 
     * @return
     *     possible object is
     *     {@link Node }
     *     
     */
    public Node getNode() {
        return node;
    }

    /**
     * Sets the value of the node property.
     * 
     * @param value
     *     allowed object is
     *     {@link Node }
     *     
     */
    public void setNode(Node value) {
        this.node = value;
    }

    /**
     * Gets the value of the carrierAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link CarrierAttributes }
     *     
     */
    public CarrierAttributes getCarrierAttributes() {
        return carrierAttributes;
    }

    /**
     * Sets the value of the carrierAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarrierAttributes }
     *     
     */
    public void setCarrierAttributes(CarrierAttributes value) {
        this.carrierAttributes = value;
    }

    /**
     * Gets the value of the paymentRuleList property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentRuleList }
     *     
     */
    public PaymentRuleList getPaymentRuleList() {
        return paymentRuleList;
    }

    /**
     * Sets the value of the paymentRuleList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentRuleList }
     *     
     */
    public void setPaymentRuleList(PaymentRuleList value) {
        this.paymentRuleList = value;
    }

    /**
     * Gets the value of the paymentTypeList property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentTypeList }
     *     
     */
    public PaymentTypeList getPaymentTypeList() {
        return paymentTypeList;
    }

    /**
     * Sets the value of the paymentTypeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentTypeList }
     *     
     */
    public void setPaymentTypeList(PaymentTypeList value) {
        this.paymentTypeList = value;
    }

    /**
     * Gets the value of the orgRoleList property.
     * 
     * @return
     *     possible object is
     *     {@link OrgRoleList }
     *     
     */
    public OrgRoleList getOrgRoleList() {
        return orgRoleList;
    }

    /**
     * Sets the value of the orgRoleList property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgRoleList }
     *     
     */
    public void setOrgRoleList(OrgRoleList value) {
        this.orgRoleList = value;
    }

    /**
     * Gets the value of the orgServiceList property.
     * 
     * @return
     *     possible object is
     *     {@link OrgServiceList }
     *     
     */
    public OrgServiceList getOrgServiceList() {
        return orgServiceList;
    }

    /**
     * Sets the value of the orgServiceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgServiceList }
     *     
     */
    public void setOrgServiceList(OrgServiceList value) {
        this.orgServiceList = value;
    }

    /**
     * Gets the value of the buyerInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link BuyerInstructions }
     *     
     */
    public BuyerInstructions getBuyerInstructions() {
        return buyerInstructions;
    }

    /**
     * Sets the value of the buyerInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuyerInstructions }
     *     
     */
    public void setBuyerInstructions(BuyerInstructions value) {
        this.buyerInstructions = value;
    }

    /**
     * Gets the value of the orgThemeList property.
     * 
     * @return
     *     possible object is
     *     {@link OrgThemeList }
     *     
     */
    public OrgThemeList getOrgThemeList() {
        return orgThemeList;
    }

    /**
     * Sets the value of the orgThemeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgThemeList }
     *     
     */
    public void setOrgThemeList(OrgThemeList value) {
        this.orgThemeList = value;
    }

    /**
     * Gets the value of the enterpriseCostPurposes property.
     * 
     * @return
     *     possible object is
     *     {@link EnterpriseCostPurposes }
     *     
     */
    public EnterpriseCostPurposes getEnterpriseCostPurposes() {
        return enterpriseCostPurposes;
    }

    /**
     * Sets the value of the enterpriseCostPurposes property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnterpriseCostPurposes }
     *     
     */
    public void setEnterpriseCostPurposes(EnterpriseCostPurposes value) {
        this.enterpriseCostPurposes = value;
    }

    /**
     * Gets the value of the sellerCostPurposes property.
     * 
     * @return
     *     possible object is
     *     {@link SellerCostPurposes }
     *     
     */
    public SellerCostPurposes getSellerCostPurposes() {
        return sellerCostPurposes;
    }

    /**
     * Sets the value of the sellerCostPurposes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SellerCostPurposes }
     *     
     */
    public void setSellerCostPurposes(SellerCostPurposes value) {
        this.sellerCostPurposes = value;
    }

}
