//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.04 at 09:40:37 AM CST 
//


package com.mozu.sterling.model.organization;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contactPersonInfo",
    "billingPersonInfo",
    "queueSubscriptionList",
    "userGroupLists",
    "userDelegateList"
})
@XmlRootElement(name = "User")
public class User {

    @XmlAttribute(name = "Activateflag")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String activateflag;
    @XmlAttribute(name = "BillingaddressKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String billingaddressKey;
    @XmlAttribute(name = "BusinessKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String businessKey;
    @XmlAttribute(name = "ContactaddressKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String contactaddressKey;
    @XmlAttribute(name = "CreatorOrganizationKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String creatorOrganizationKey;
    @XmlAttribute(name = "Imagefile")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String imagefile;
    @XmlAttribute(name = "Localecode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String localecode;
    @XmlAttribute(name = "Loginid")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String loginid;
    @XmlAttribute(name = "Longdesc")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String longdesc;
    @XmlAttribute(name = "MenuId")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String menuId;
    @XmlAttribute(name = "NoteKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String noteKey;
    @XmlAttribute(name = "OrganizationKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String organizationKey;
    @XmlAttribute(name = "ParentUserKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String parentUserKey;
    @XmlAttribute(name = "Password")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String password;
    @XmlAttribute(name = "PasswordPolicyKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String passwordPolicyKey;
    @XmlAttribute(name = "PreferenceKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String preferenceKey;
    @XmlAttribute(name = "Pwdlastchangedon")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pwdlastchangedon;
    @XmlAttribute(name = "Theme")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String theme;
    @XmlAttribute(name = "UserKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String userKey;
    @XmlAttribute(name = "UsergroupKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String usergroupKey;
    @XmlAttribute(name = "Username")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String username;
    @XmlAttribute(name = "Usertype")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String usertype;
    @XmlAttribute(name = "a-dtype")
    protected List<String> aDtype;
    @XmlElement(name = "ContactPersonInfo")
    protected ContactPersonInfo contactPersonInfo;
    @XmlElement(name = "BillingPersonInfo")
    protected BillingPersonInfo billingPersonInfo;
    @XmlElement(name = "QueueSubscriptionList")
    protected QueueSubscriptionList queueSubscriptionList;
    @XmlElement(name = "UserGroupLists")
    protected UserGroupLists userGroupLists;
    @XmlElement(name = "UserDelegateList")
    protected UserDelegateList userDelegateList;

    /**
     * Gets the value of the activateflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivateflag() {
        return activateflag;
    }

    /**
     * Sets the value of the activateflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivateflag(String value) {
        this.activateflag = value;
    }

    /**
     * Gets the value of the billingaddressKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingaddressKey() {
        return billingaddressKey;
    }

    /**
     * Sets the value of the billingaddressKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingaddressKey(String value) {
        this.billingaddressKey = value;
    }

    /**
     * Gets the value of the businessKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessKey() {
        return businessKey;
    }

    /**
     * Sets the value of the businessKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessKey(String value) {
        this.businessKey = value;
    }

    /**
     * Gets the value of the contactaddressKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactaddressKey() {
        return contactaddressKey;
    }

    /**
     * Sets the value of the contactaddressKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactaddressKey(String value) {
        this.contactaddressKey = value;
    }

    /**
     * Gets the value of the creatorOrganizationKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatorOrganizationKey() {
        return creatorOrganizationKey;
    }

    /**
     * Sets the value of the creatorOrganizationKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatorOrganizationKey(String value) {
        this.creatorOrganizationKey = value;
    }

    /**
     * Gets the value of the imagefile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImagefile() {
        return imagefile;
    }

    /**
     * Sets the value of the imagefile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImagefile(String value) {
        this.imagefile = value;
    }

    /**
     * Gets the value of the localecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalecode() {
        return localecode;
    }

    /**
     * Sets the value of the localecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalecode(String value) {
        this.localecode = value;
    }

    /**
     * Gets the value of the loginid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoginid() {
        return loginid;
    }

    /**
     * Sets the value of the loginid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoginid(String value) {
        this.loginid = value;
    }

    /**
     * Gets the value of the longdesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongdesc() {
        return longdesc;
    }

    /**
     * Sets the value of the longdesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongdesc(String value) {
        this.longdesc = value;
    }

    /**
     * Gets the value of the menuId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * Sets the value of the menuId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMenuId(String value) {
        this.menuId = value;
    }

    /**
     * Gets the value of the noteKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoteKey() {
        return noteKey;
    }

    /**
     * Sets the value of the noteKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoteKey(String value) {
        this.noteKey = value;
    }

    /**
     * Gets the value of the organizationKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationKey() {
        return organizationKey;
    }

    /**
     * Sets the value of the organizationKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationKey(String value) {
        this.organizationKey = value;
    }

    /**
     * Gets the value of the parentUserKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentUserKey() {
        return parentUserKey;
    }

    /**
     * Sets the value of the parentUserKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentUserKey(String value) {
        this.parentUserKey = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the passwordPolicyKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasswordPolicyKey() {
        return passwordPolicyKey;
    }

    /**
     * Sets the value of the passwordPolicyKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasswordPolicyKey(String value) {
        this.passwordPolicyKey = value;
    }

    /**
     * Gets the value of the preferenceKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferenceKey() {
        return preferenceKey;
    }

    /**
     * Sets the value of the preferenceKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferenceKey(String value) {
        this.preferenceKey = value;
    }

    /**
     * Gets the value of the pwdlastchangedon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPwdlastchangedon() {
        return pwdlastchangedon;
    }

    /**
     * Sets the value of the pwdlastchangedon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPwdlastchangedon(String value) {
        this.pwdlastchangedon = value;
    }

    /**
     * Gets the value of the theme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTheme() {
        return theme;
    }

    /**
     * Sets the value of the theme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTheme(String value) {
        this.theme = value;
    }

    /**
     * Gets the value of the userKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserKey() {
        return userKey;
    }

    /**
     * Sets the value of the userKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserKey(String value) {
        this.userKey = value;
    }

    /**
     * Gets the value of the usergroupKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsergroupKey() {
        return usergroupKey;
    }

    /**
     * Sets the value of the usergroupKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsergroupKey(String value) {
        this.usergroupKey = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the usertype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * Sets the value of the usertype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsertype(String value) {
        this.usertype = value;
    }

    /**
     * Gets the value of the aDtype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aDtype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getADtype().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getADtype() {
        if (aDtype == null) {
            aDtype = new ArrayList<String>();
        }
        return this.aDtype;
    }

    /**
     * Gets the value of the contactPersonInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ContactPersonInfo }
     *     
     */
    public ContactPersonInfo getContactPersonInfo() {
        return contactPersonInfo;
    }

    /**
     * Sets the value of the contactPersonInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactPersonInfo }
     *     
     */
    public void setContactPersonInfo(ContactPersonInfo value) {
        this.contactPersonInfo = value;
    }

    /**
     * Gets the value of the billingPersonInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BillingPersonInfo }
     *     
     */
    public BillingPersonInfo getBillingPersonInfo() {
        return billingPersonInfo;
    }

    /**
     * Sets the value of the billingPersonInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillingPersonInfo }
     *     
     */
    public void setBillingPersonInfo(BillingPersonInfo value) {
        this.billingPersonInfo = value;
    }

    /**
     * Gets the value of the queueSubscriptionList property.
     * 
     * @return
     *     possible object is
     *     {@link QueueSubscriptionList }
     *     
     */
    public QueueSubscriptionList getQueueSubscriptionList() {
        return queueSubscriptionList;
    }

    /**
     * Sets the value of the queueSubscriptionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueueSubscriptionList }
     *     
     */
    public void setQueueSubscriptionList(QueueSubscriptionList value) {
        this.queueSubscriptionList = value;
    }

    /**
     * Gets the value of the userGroupLists property.
     * 
     * @return
     *     possible object is
     *     {@link UserGroupLists }
     *     
     */
    public UserGroupLists getUserGroupLists() {
        return userGroupLists;
    }

    /**
     * Sets the value of the userGroupLists property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserGroupLists }
     *     
     */
    public void setUserGroupLists(UserGroupLists value) {
        this.userGroupLists = value;
    }

    /**
     * Gets the value of the userDelegateList property.
     * 
     * @return
     *     possible object is
     *     {@link UserDelegateList }
     *     
     */
    public UserDelegateList getUserDelegateList() {
        return userDelegateList;
    }

    /**
     * Sets the value of the userDelegateList property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDelegateList }
     *     
     */
    public void setUserDelegateList(UserDelegateList value) {
        this.userDelegateList = value;
    }

}
