//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 01:47:34 PM CST 
//


package com.mozu.sterling.model.shipping;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "CarrierService")
public class CarrierService {

    @XmlAttribute(name = "CarrierServiceCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String carrierServiceCode;
    @XmlAttribute(name = "CarrierServiceDesc")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String carrierServiceDesc;
    @XmlAttribute(name = "CarrierServiceKey")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String carrierServiceKey;
    @XmlAttribute(name = "MaximumNontransitDays")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String maximumNontransitDays;
    @XmlAttribute(name = "MaximumTransitDays")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String maximumTransitDays;
    @XmlAttribute(name = "MinimumTransitDays")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String minimumTransitDays;
    @XmlAttribute(name = "OrganizationCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String organizationCode;
    @XmlAttribute(name = "SCAC")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String scac;
    @XmlAttribute(name = "SCACAndService")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String scacAndService;
    @XmlAttribute(name = "SCACAndServiceDesc")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String scacAndServiceDesc;
    @XmlAttribute(name = "SCACDesc")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String scacDesc;
    @XmlAttribute(name = "UsedForOrdering")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String usedForOrdering;
    @XmlAttribute(name = "a-dtype")
    protected List<String> aDtype;

    /**
     * Gets the value of the carrierServiceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrierServiceCode() {
        return carrierServiceCode;
    }

    /**
     * Sets the value of the carrierServiceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrierServiceCode(String value) {
        this.carrierServiceCode = value;
    }

    /**
     * Gets the value of the carrierServiceDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrierServiceDesc() {
        return carrierServiceDesc;
    }

    /**
     * Sets the value of the carrierServiceDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrierServiceDesc(String value) {
        this.carrierServiceDesc = value;
    }

    /**
     * Gets the value of the carrierServiceKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrierServiceKey() {
        return carrierServiceKey;
    }

    /**
     * Sets the value of the carrierServiceKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrierServiceKey(String value) {
        this.carrierServiceKey = value;
    }

    /**
     * Gets the value of the maximumNontransitDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaximumNontransitDays() {
        return maximumNontransitDays;
    }

    /**
     * Sets the value of the maximumNontransitDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaximumNontransitDays(String value) {
        this.maximumNontransitDays = value;
    }

    /**
     * Gets the value of the maximumTransitDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaximumTransitDays() {
        return maximumTransitDays;
    }

    /**
     * Sets the value of the maximumTransitDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaximumTransitDays(String value) {
        this.maximumTransitDays = value;
    }

    /**
     * Gets the value of the minimumTransitDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinimumTransitDays() {
        return minimumTransitDays;
    }

    /**
     * Sets the value of the minimumTransitDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinimumTransitDays(String value) {
        this.minimumTransitDays = value;
    }

    /**
     * Gets the value of the organizationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationCode() {
        return organizationCode;
    }

    /**
     * Sets the value of the organizationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationCode(String value) {
        this.organizationCode = value;
    }

    /**
     * Gets the value of the scac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCAC() {
        return scac;
    }

    /**
     * Sets the value of the scac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCAC(String value) {
        this.scac = value;
    }

    /**
     * Gets the value of the scacAndService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCACAndService() {
        return scacAndService;
    }

    /**
     * Sets the value of the scacAndService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCACAndService(String value) {
        this.scacAndService = value;
    }

    /**
     * Gets the value of the scacAndServiceDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCACAndServiceDesc() {
        return scacAndServiceDesc;
    }

    /**
     * Sets the value of the scacAndServiceDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCACAndServiceDesc(String value) {
        this.scacAndServiceDesc = value;
    }

    /**
     * Gets the value of the scacDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCACDesc() {
        return scacDesc;
    }

    /**
     * Sets the value of the scacDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCACDesc(String value) {
        this.scacDesc = value;
    }

    /**
     * Gets the value of the usedForOrdering property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsedForOrdering() {
        return usedForOrdering;
    }

    /**
     * Sets the value of the usedForOrdering property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsedForOrdering(String value) {
        this.usedForOrdering = value;
    }

    /**
     * Gets the value of the aDtype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aDtype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getADtype().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getADtype() {
        if (aDtype == null) {
            aDtype = new ArrayList<String>();
        }
        return this.aDtype;
    }

}
